/**
 * Firestoreシードスクリプト
 * 実行: npx ts-node --project tsconfig.seed.json scripts/seed-usecases.ts
 *
 * 事前準備:
 *   1. Firebase Console → プロジェクト設定 → サービス アカウント → 新しい秘密鍵を生成
 *   2. export GOOGLE_APPLICATION_CREDENTIALS="./serviceAccountKey.json"
 */

import { initializeApp, cert, ServiceAccount } from "firebase-admin/app";
import { getFirestore, FieldValue } from "firebase-admin/firestore";
import * as path from "path";

const keyPath = process.env.GOOGLE_APPLICATION_CREDENTIALS;
if (!keyPath) {
  console.error("GOOGLE_APPLICATION_CREDENTIALS が未設定です");
  process.exit(1);
}

initializeApp({ credential: cert(require(path.resolve(keyPath)) as ServiceAccount) });
const db = getFirestore();

const TEMPLATE_CATEGORY_SLUG: Record<string, string> = {
  "tpl-shelf-basic":   "tana",
  "tpl-planter-stand": "planter-dai",
  "tpl-compost-box":   "compost",
  "tpl-bench":         "bench",
  "tpl-deck":          "deck",
  "tpl-shoe-rack":     "shoe-rack",
  "tpl-flower-box":    "flower-box",
  "tpl-hanger-rack":   "hanger-rack",
  "tpl-garden-table":  "garden-table",
  "tpl-tv-stand":      "tv-stand",
  "tpl-bookshelf":     "bookshelf",
  "tpl-cat-walk":      "cat-walk",
};

const ALL_USE_CASES = [
  { id: "shelf-1", name: "シンプル壁面棚", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-2", name: "オープン収納棚", difficulty: "初心者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-3", name: "キッチン吊り棚", difficulty: "中級者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 150, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-4", name: "ディアウォール棚", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-5", name: "L字型コーナー棚", difficulty: "中級者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-6", name: "階段下収納棚", difficulty: "中級者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-7", name: "ベッドサイドシェルフ", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 5000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-8", name: "玄関飾り棚", difficulty: "初心者", estimatedBudgetMin: 2500, estimatedBudgetMax: 5000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-9", name: "多段壁面収納", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-10", name: "子供部屋絵本棚", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-11", name: "キッチンスパイスラック", difficulty: "初心者", estimatedBudgetMin: 1500, estimatedBudgetMax: 3000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-12", name: "ランドリーラック", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-13", name: "バスルーム棚", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-14", name: "ガレージ工具棚", difficulty: "中級者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-15", name: "アンティーク風壁棚", difficulty: "中級者", estimatedBudgetMin: 4000, estimatedBudgetMax: 9000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-16", name: "フロートシェルフ", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4500, estimatedTimeMinutes: 60, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-17", name: "作業部屋工具棚", difficulty: "中級者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-18", name: "脱衣所タオル棚", difficulty: "初心者", estimatedBudgetMin: 2500, estimatedBudgetMax: 5000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-19", name: "店舗ディスプレイ棚", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 16000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "shelf-20", name: "可動仕切り収納棚", difficulty: "上級者", estimatedBudgetMin: 12000, estimatedBudgetMax: 25000, estimatedTimeMinutes: 480, indoorOutdoor: "屋内", category: "棚", templateID: "tpl-shelf-basic" },
  { id: "planter-1", name: "プランタースタンド", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内・屋外", category: "プランター台", templateID: "tpl-planter-stand" },
  { id: "planter-2", name: "ガーデンプランタースタンド", difficulty: "中級者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 240, indoorOutdoor: "屋外", category: "プランター台", templateID: "tpl-planter-stand" },
  { id: "planter-3", name: "多段プランターラダー", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内・屋外", category: "プランター台", templateID: "tpl-planter-stand" },
  { id: "planter-4", name: "ミニプランター台", difficulty: "初心者", estimatedBudgetMin: 1000, estimatedBudgetMax: 2500, estimatedTimeMinutes: 45, indoorOutdoor: "屋内・屋外", category: "プランター台", templateID: "tpl-planter-stand" },
  { id: "planter-5", name: "コーナープランター台", difficulty: "初心者", estimatedBudgetMin: 2500, estimatedBudgetMax: 5000, estimatedTimeMinutes: 90, indoorOutdoor: "屋外", category: "プランター台", templateID: "tpl-planter-stand" },
  { id: "planter-6", name: "フェンス付きプランタースタンド", difficulty: "中級者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 240, indoorOutdoor: "屋外", category: "プランター台", templateID: "tpl-planter-stand" },
  { id: "planter-7", name: "ハーブ用プランター棚", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内・屋外", category: "プランター台", templateID: "tpl-planter-stand" },
  { id: "planter-8", name: "バルコニープランター台", difficulty: "初心者", estimatedBudgetMin: 2500, estimatedBudgetMax: 5000, estimatedTimeMinutes: 90, indoorOutdoor: "屋外", category: "プランター台", templateID: "tpl-planter-stand" },
  { id: "planter-9", name: "スタッキングプランター台", difficulty: "中級者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内・屋外", category: "プランター台", templateID: "tpl-planter-stand" },
  { id: "planter-10", name: "ウッドプランターボックス", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 120, indoorOutdoor: "屋外", category: "プランター台", templateID: "tpl-planter-stand" },
  { id: "compost-1", name: "木製コンポストボックス", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 360, indoorOutdoor: "屋外", category: "コンポスト", templateID: "tpl-compost-box" },
  { id: "compost-2", name: "2層式コンポストボックス", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 18000, estimatedTimeMinutes: 420, indoorOutdoor: "屋外", category: "コンポスト", templateID: "tpl-compost-box" },
  { id: "compost-3", name: "ミミズ堆肥コンポスター", difficulty: "初心者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋外", category: "コンポスト", templateID: "tpl-compost-box" },
  { id: "compost-4", name: "コンポスト収納ボックス", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 150, indoorOutdoor: "屋外", category: "コンポスト", templateID: "tpl-compost-box" },
  { id: "compost-5", name: "大型コンポストボックス", difficulty: "上級者", estimatedBudgetMin: 15000, estimatedBudgetMax: 25000, estimatedTimeMinutes: 540, indoorOutdoor: "屋外", category: "コンポスト", templateID: "tpl-compost-box" },
  { id: "bench-1", name: "シンプルウッドベンチ", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内・屋外", category: "ベンチ", templateID: "tpl-bench" },
  { id: "bench-2", name: "ガーデンベンチ", difficulty: "中級者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋外", category: "ベンチ", templateID: "tpl-bench" },
  { id: "bench-3", name: "背もたれ付きベンチ", difficulty: "中級者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内・屋外", category: "ベンチ", templateID: "tpl-bench" },
  { id: "bench-4", name: "収納付きベンチ", difficulty: "中級者", estimatedBudgetMin: 7000, estimatedBudgetMax: 14000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "ベンチ", templateID: "tpl-bench" },
  { id: "bench-5", name: "コーナーベンチ", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 300, indoorOutdoor: "屋外", category: "ベンチ", templateID: "tpl-bench" },
  { id: "bench-6", name: "ベンチチェア（小型）", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内・屋外", category: "ベンチ", templateID: "tpl-bench" },
  { id: "bench-7", name: "縁側風ベンチ", difficulty: "中級者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 240, indoorOutdoor: "屋外", category: "ベンチ", templateID: "tpl-bench" },
  { id: "bench-8", name: "バルコニーベンチ", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋外", category: "ベンチ", templateID: "tpl-bench" },
  { id: "bench-9", name: "公園風ベンチ", difficulty: "中級者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋外", category: "ベンチ", templateID: "tpl-bench" },
  { id: "bench-10", name: "子供用ローベンチ", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "ベンチ", templateID: "tpl-bench" },
  { id: "bench-11", name: "玄関用ベンチ", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "ベンチ", templateID: "tpl-bench" },
  { id: "bench-12", name: "ピクニックベンチ", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 120, indoorOutdoor: "屋外", category: "ベンチ", templateID: "tpl-bench" },
  { id: "bench-13", name: "植木鉢台兼ベンチ", difficulty: "中級者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋外", category: "ベンチ", templateID: "tpl-bench" },
  { id: "bench-14", name: "折りたたみベンチ", difficulty: "中級者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 150, indoorOutdoor: "屋内・屋外", category: "ベンチ", templateID: "tpl-bench" },
  { id: "bench-15", name: "テラスデイベッド", difficulty: "上級者", estimatedBudgetMin: 15000, estimatedBudgetMax: 30000, estimatedTimeMinutes: 480, indoorOutdoor: "屋外", category: "ベンチ", templateID: "tpl-bench" },
  { id: "garden-table-1", name: "ガーデンテーブル", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 240, indoorOutdoor: "屋外", category: "ガーデンテーブル", templateID: "tpl-garden-table" },
  { id: "garden-table-2", name: "ピクニックテーブル（ベンチ一体型）", difficulty: "中級者", estimatedBudgetMin: 12000, estimatedBudgetMax: 20000, estimatedTimeMinutes: 360, indoorOutdoor: "屋外", category: "ガーデンテーブル", templateID: "tpl-garden-table" },
  { id: "garden-table-3", name: "ラウンドガーデンテーブル", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 18000, estimatedTimeMinutes: 300, indoorOutdoor: "屋外", category: "ガーデンテーブル", templateID: "tpl-garden-table" },
  { id: "garden-table-4", name: "フォールディングガーデンテーブル", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋外", category: "ガーデンテーブル", templateID: "tpl-garden-table" },
  { id: "garden-table-5", name: "バルコニー小テーブル", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋外", category: "ガーデンテーブル", templateID: "tpl-garden-table" },
  { id: "garden-table-6", name: "カフェ風ガーデンテーブル", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 240, indoorOutdoor: "屋外", category: "ガーデンテーブル", templateID: "tpl-garden-table" },
  { id: "garden-table-7", name: "BBQテーブル", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 20000, estimatedTimeMinutes: 300, indoorOutdoor: "屋外", category: "ガーデンテーブル", templateID: "tpl-garden-table" },
  { id: "garden-table-8", name: "縁台テーブル", difficulty: "中級者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 240, indoorOutdoor: "屋外", category: "ガーデンテーブル", templateID: "tpl-garden-table" },
  { id: "garden-table-9", name: "六角形ピクニックテーブル", difficulty: "上級者", estimatedBudgetMin: 20000, estimatedBudgetMax: 35000, estimatedTimeMinutes: 540, indoorOutdoor: "屋外", category: "ガーデンテーブル", templateID: "tpl-garden-table" },
  { id: "garden-table-10", name: "キャンプ用ロールテーブル", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 7000, estimatedTimeMinutes: 120, indoorOutdoor: "屋外", category: "ガーデンテーブル", templateID: "tpl-garden-table" },
  { id: "shoe-rack-1", name: "玄関シューズラック", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 100, indoorOutdoor: "屋内", category: "シューズラック", templateID: "tpl-shoe-rack" },
  { id: "shoe-rack-2", name: "大容量シューズボックス", difficulty: "中級者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 200, indoorOutdoor: "屋内", category: "シューズラック", templateID: "tpl-shoe-rack" },
  { id: "shoe-rack-3", name: "傘立て付きシューズラック", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "シューズラック", templateID: "tpl-shoe-rack" },
  { id: "shoe-rack-4", name: "ベンチ一体型シューズラック", difficulty: "中級者", estimatedBudgetMin: 7000, estimatedBudgetMax: 14000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "シューズラック", templateID: "tpl-shoe-rack" },
  { id: "shoe-rack-5", name: "スリムシューズラック", difficulty: "初心者", estimatedBudgetMin: 2500, estimatedBudgetMax: 5000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "シューズラック", templateID: "tpl-shoe-rack" },
  { id: "shoe-rack-6", name: "靴磨き台付きシューズラック", difficulty: "中級者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内", category: "シューズラック", templateID: "tpl-shoe-rack" },
  { id: "shoe-rack-7", name: "スタッキングシューズラック", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "シューズラック", templateID: "tpl-shoe-rack" },
  { id: "shoe-rack-8", name: "アウトドアシューズラック", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋外", category: "シューズラック", templateID: "tpl-shoe-rack" },
  { id: "shoe-rack-9", name: "子供用シューズラック", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内", category: "シューズラック", templateID: "tpl-shoe-rack" },
  { id: "shoe-rack-10", name: "壁掛け玄関収納", difficulty: "中級者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 150, indoorOutdoor: "屋内", category: "シューズラック", templateID: "tpl-shoe-rack" },
  { id: "flower-box-1", name: "ウィンドウフラワーボックス", difficulty: "初心者", estimatedBudgetMin: 1500, estimatedBudgetMax: 3500, estimatedTimeMinutes: 60, indoorOutdoor: "屋外", category: "フラワーボックス", templateID: "tpl-flower-box" },
  { id: "flower-box-2", name: "ガーデンフラワーボックス（長尺）", difficulty: "初心者", estimatedBudgetMin: 2500, estimatedBudgetMax: 5000, estimatedTimeMinutes: 90, indoorOutdoor: "屋外", category: "フラワーボックス", templateID: "tpl-flower-box" },
  { id: "flower-box-3", name: "ハンギングフラワーボックス", difficulty: "初心者", estimatedBudgetMin: 1500, estimatedBudgetMax: 3000, estimatedTimeMinutes: 60, indoorOutdoor: "屋外", category: "フラワーボックス", templateID: "tpl-flower-box" },
  { id: "flower-box-4", name: "ウォールフラワーポット", difficulty: "初心者", estimatedBudgetMin: 1000, estimatedBudgetMax: 2500, estimatedTimeMinutes: 45, indoorOutdoor: "屋外", category: "フラワーボックス", templateID: "tpl-flower-box" },
  { id: "flower-box-5", name: "ミニハーブガーデンボックス", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内・屋外", category: "フラワーボックス", templateID: "tpl-flower-box" },
  { id: "flower-box-6", name: "フェンス取付フラワーボックス", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 60, indoorOutdoor: "屋外", category: "フラワーボックス", templateID: "tpl-flower-box" },
  { id: "flower-box-7", name: "木製プランターポット", difficulty: "初心者", estimatedBudgetMin: 2500, estimatedBudgetMax: 5000, estimatedTimeMinutes: 90, indoorOutdoor: "屋外", category: "フラワーボックス", templateID: "tpl-flower-box" },
  { id: "flower-box-8", name: "コーナーフラワーボックス", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 75, indoorOutdoor: "屋外", category: "フラワーボックス", templateID: "tpl-flower-box" },
  { id: "flower-box-9", name: "バルコニーフラワーボックス", difficulty: "初心者", estimatedBudgetMin: 2500, estimatedBudgetMax: 5000, estimatedTimeMinutes: 90, indoorOutdoor: "屋外", category: "フラワーボックス", templateID: "tpl-flower-box" },
  { id: "flower-box-10", name: "アンティーク木箱フラワーボックス", difficulty: "中級者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内・屋外", category: "フラワーボックス", templateID: "tpl-flower-box" },
  { id: "tv-stand-1", name: "シンプルTV台", difficulty: "初心者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 150, indoorOutdoor: "屋内", category: "TV台", templateID: "tpl-tv-stand" },
  { id: "tv-stand-2", name: "収納付きローボード", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "TV台", templateID: "tpl-tv-stand" },
  { id: "tv-stand-3", name: "壁掛け風TV台", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "TV台", templateID: "tpl-tv-stand" },
  { id: "tv-stand-4", name: "引き出し付きTV台", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 18000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "TV台", templateID: "tpl-tv-stand" },
  { id: "tv-stand-5", name: "TV台兼本棚", difficulty: "中級者", estimatedBudgetMin: 12000, estimatedBudgetMax: 22000, estimatedTimeMinutes: 360, indoorOutdoor: "屋内", category: "TV台", templateID: "tpl-tv-stand" },
  { id: "tv-stand-6", name: "天然木TV台", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 20000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "TV台", templateID: "tpl-tv-stand" },
  { id: "tv-stand-7", name: "アイアン脚TV台", difficulty: "上級者", estimatedBudgetMin: 12000, estimatedBudgetMax: 22000, estimatedTimeMinutes: 360, indoorOutdoor: "屋内", category: "TV台", templateID: "tpl-tv-stand" },
  { id: "tv-stand-8", name: "コーナーTV台", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 16000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "TV台", templateID: "tpl-tv-stand" },
  { id: "tv-stand-9", name: "マルチメディアラック", difficulty: "中級者", estimatedBudgetMin: 9000, estimatedBudgetMax: 18000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "TV台", templateID: "tpl-tv-stand" },
  { id: "tv-stand-10", name: "リビング収納ボード", difficulty: "上級者", estimatedBudgetMin: 15000, estimatedBudgetMax: 28000, estimatedTimeMinutes: 480, indoorOutdoor: "屋内", category: "TV台", templateID: "tpl-tv-stand" },
  { id: "wood-deck-1", name: "ミニウッドデッキ", difficulty: "中級者", estimatedBudgetMin: 20000, estimatedBudgetMax: 40000, estimatedTimeMinutes: 480, indoorOutdoor: "屋外", category: "ウッドデッキ", templateID: "tpl-wood-deck" },
  { id: "wood-deck-2", name: "ウッドデッキ（大型）", difficulty: "上級者", estimatedBudgetMin: 50000, estimatedBudgetMax: 100000, estimatedTimeMinutes: 960, indoorOutdoor: "屋外", category: "ウッドデッキ", templateID: "tpl-wood-deck" },
  { id: "wood-deck-3", name: "バルコニーウッドデッキ", difficulty: "中級者", estimatedBudgetMin: 15000, estimatedBudgetMax: 30000, estimatedTimeMinutes: 360, indoorOutdoor: "屋外", category: "ウッドデッキ", templateID: "tpl-wood-deck" },
  { id: "wood-deck-4", name: "縁台（縁側デッキ）", difficulty: "初心者", estimatedBudgetMin: 8000, estimatedBudgetMax: 16000, estimatedTimeMinutes: 240, indoorOutdoor: "屋外", category: "ウッドデッキ", templateID: "tpl-wood-deck" },
  { id: "wood-deck-5", name: "アジアン風デッキ", difficulty: "中級者", estimatedBudgetMin: 25000, estimatedBudgetMax: 50000, estimatedTimeMinutes: 600, indoorOutdoor: "屋外", category: "ウッドデッキ", templateID: "tpl-wood-deck" },
  { id: "wood-deck-6", name: "手すり付きウッドデッキ", difficulty: "上級者", estimatedBudgetMin: 35000, estimatedBudgetMax: 70000, estimatedTimeMinutes: 720, indoorOutdoor: "屋外", category: "ウッドデッキ", templateID: "tpl-wood-deck" },
  { id: "wood-deck-7", name: "段差解消デッキ", difficulty: "中級者", estimatedBudgetMin: 12000, estimatedBudgetMax: 25000, estimatedTimeMinutes: 360, indoorOutdoor: "屋外", category: "ウッドデッキ", templateID: "tpl-wood-deck" },
  { id: "wood-deck-8", name: "プールデッキ", difficulty: "中級者", estimatedBudgetMin: 18000, estimatedBudgetMax: 35000, estimatedTimeMinutes: 420, indoorOutdoor: "屋外", category: "ウッドデッキ", templateID: "tpl-wood-deck" },
  { id: "wood-deck-9", name: "テラスデッキ（屋根なし）", difficulty: "中級者", estimatedBudgetMin: 22000, estimatedBudgetMax: 45000, estimatedTimeMinutes: 540, indoorOutdoor: "屋外", category: "ウッドデッキ", templateID: "tpl-wood-deck" },
  { id: "wood-deck-10", name: "ルーフデッキ（屋上）", difficulty: "上級者", estimatedBudgetMin: 60000, estimatedBudgetMax: 120000, estimatedTimeMinutes: 1200, indoorOutdoor: "屋外", category: "ウッドデッキ", templateID: "tpl-wood-deck" },
  { id: "cat-walk-1", name: "壁付けキャットステップ", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 5000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内", category: "キャットウォーク", templateID: "tpl-cat-walk" },
  { id: "cat-walk-2", name: "キャットタワー一体型ウォーク", difficulty: "中級者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "キャットウォーク", templateID: "tpl-cat-walk" },
  { id: "cat-walk-3", name: "棚板式キャットウォーク", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 7000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "キャットウォーク", templateID: "tpl-cat-walk" },
  { id: "cat-walk-4", name: "コーナーキャットシェルフ", difficulty: "初心者", estimatedBudgetMin: 2500, estimatedBudgetMax: 5000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内", category: "キャットウォーク", templateID: "tpl-cat-walk" },
  { id: "cat-walk-5", name: "猫用隠れ家付きウォーク", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "キャットウォーク", templateID: "tpl-cat-walk" },
  { id: "cat-walk-6", name: "吊り橋式キャットウォーク", difficulty: "中級者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内", category: "キャットウォーク", templateID: "tpl-cat-walk" },
  { id: "cat-walk-7", name: "ミニキャットウォーク", difficulty: "初心者", estimatedBudgetMin: 1500, estimatedBudgetMax: 3500, estimatedTimeMinutes: 45, indoorOutdoor: "屋内", category: "キャットウォーク", templateID: "tpl-cat-walk" },
  { id: "cat-walk-8", name: "猫用はしご", difficulty: "初心者", estimatedBudgetMin: 1500, estimatedBudgetMax: 3000, estimatedTimeMinutes: 45, indoorOutdoor: "屋内", category: "キャットウォーク", templateID: "tpl-cat-walk" },
  { id: "cat-walk-9", name: "猫用窓辺ベッド", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内", category: "キャットウォーク", templateID: "tpl-cat-walk" },
  { id: "cat-walk-10", name: "窓際キャットステップ", difficulty: "初心者", estimatedBudgetMin: 2500, estimatedBudgetMax: 5000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内", category: "キャットウォーク", templateID: "tpl-cat-walk" },
  { id: "dog-house-1", name: "小型犬用木製犬小屋", difficulty: "初心者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋外", category: "犬小屋", templateID: "tpl-compost-box" },
  { id: "dog-house-2", name: "中型犬用犬小屋", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 300, indoorOutdoor: "屋外", category: "犬小屋", templateID: "tpl-compost-box" },
  { id: "dog-house-3", name: "大型犬用犬小屋", difficulty: "中級者", estimatedBudgetMin: 12000, estimatedBudgetMax: 25000, estimatedTimeMinutes: 420, indoorOutdoor: "屋外", category: "犬小屋", templateID: "tpl-compost-box" },
  { id: "dog-house-4", name: "屋根付き高床式犬小屋", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 20000, estimatedTimeMinutes: 360, indoorOutdoor: "屋外", category: "犬小屋", templateID: "tpl-compost-box" },
  { id: "dog-house-5", name: "ドア付き犬小屋", difficulty: "初心者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 240, indoorOutdoor: "屋外", category: "犬小屋", templateID: "tpl-compost-box" },
  { id: "dog-house-6", name: "断熱ペットハウス", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 20000, estimatedTimeMinutes: 360, indoorOutdoor: "屋外", category: "犬小屋", templateID: "tpl-compost-box" },
  { id: "dog-house-7", name: "縁側付き犬小屋", difficulty: "上級者", estimatedBudgetMin: 15000, estimatedBudgetMax: 30000, estimatedTimeMinutes: 540, indoorOutdoor: "屋外", category: "犬小屋", templateID: "tpl-compost-box" },
  { id: "dog-house-8", name: "ミニチュアハウス型犬小屋", difficulty: "上級者", estimatedBudgetMin: 18000, estimatedBudgetMax: 35000, estimatedTimeMinutes: 600, indoorOutdoor: "屋外", category: "犬小屋", templateID: "tpl-compost-box" },
  { id: "dog-house-9", name: "折りたたみ犬用ケージカバー", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "犬小屋", templateID: "tpl-compost-box" },
  { id: "dog-house-10", name: "犬用ウッドデッキ付き犬小屋", difficulty: "上級者", estimatedBudgetMin: 25000, estimatedBudgetMax: 50000, estimatedTimeMinutes: 720, indoorOutdoor: "屋外", category: "犬小屋", templateID: "tpl-compost-box" },
  { id: "cat-tower-1", name: "シンプルキャットタワー", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 7000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "キャットタワー", templateID: "tpl-cat-walk" },
  { id: "cat-tower-2", name: "3段キャットタワー", difficulty: "中級者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "キャットタワー", templateID: "tpl-cat-walk" },
  { id: "cat-tower-3", name: "据え置き型キャットタワー", difficulty: "中級者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内", category: "キャットタワー", templateID: "tpl-cat-walk" },
  { id: "cat-tower-4", name: "壁面一体型キャットタワー", difficulty: "上級者", estimatedBudgetMin: 15000, estimatedBudgetMax: 30000, estimatedTimeMinutes: 480, indoorOutdoor: "屋内", category: "キャットタワー", templateID: "tpl-cat-walk" },
  { id: "cat-tower-5", name: "ハンモック付きキャットタワー", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "キャットタワー", templateID: "tpl-cat-walk" },
  { id: "cat-tower-6", name: "隠れ家付きキャットタワー", difficulty: "中級者", estimatedBudgetMin: 9000, estimatedBudgetMax: 18000, estimatedTimeMinutes: 360, indoorOutdoor: "屋内", category: "キャットタワー", templateID: "tpl-cat-walk" },
  { id: "cat-tower-7", name: "多頭飼い用キャットタワー", difficulty: "上級者", estimatedBudgetMin: 15000, estimatedBudgetMax: 30000, estimatedTimeMinutes: 480, indoorOutdoor: "屋内", category: "キャットタワー", templateID: "tpl-cat-walk" },
  { id: "cat-tower-8", name: "スリムキャットタワー", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "キャットタワー", templateID: "tpl-cat-walk" },
  { id: "cat-tower-9", name: "猫用ジャングルジム", difficulty: "上級者", estimatedBudgetMin: 20000, estimatedBudgetMax: 40000, estimatedTimeMinutes: 600, indoorOutdoor: "屋内", category: "キャットタワー", templateID: "tpl-cat-walk" },
  { id: "cat-tower-10", name: "突っ張り式キャットタワー", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "キャットタワー", templateID: "tpl-cat-walk" },
  { id: "pet-storage-1", name: "猫砂ボックス収納キャビネット", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "ペット用収納", templateID: "tpl-shoe-rack" },
  { id: "pet-storage-2", name: "ペットフード収納棚", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "ペット用収納", templateID: "tpl-shoe-rack" },
  { id: "pet-storage-3", name: "ペット用おもちゃ収納ボックス", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内", category: "ペット用収納", templateID: "tpl-shoe-rack" },
  { id: "pet-storage-4", name: "ペットベッド付き収納ベンチ", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "ペット用収納", templateID: "tpl-bench" },
  { id: "pet-storage-5", name: "ペット用品ラック", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "ペット用収納", templateID: "tpl-shoe-rack" },
  { id: "dining-1", name: "シンプルダイニングテーブル", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 20000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "ダイニングテーブル", templateID: "tpl-garden-table" },
  { id: "dining-2", name: "4人掛けダイニングテーブル", difficulty: "中級者", estimatedBudgetMin: 15000, estimatedBudgetMax: 28000, estimatedTimeMinutes: 360, indoorOutdoor: "屋内", category: "ダイニングテーブル", templateID: "tpl-garden-table" },
  { id: "dining-3", name: "6人掛けダイニングテーブル", difficulty: "上級者", estimatedBudgetMin: 25000, estimatedBudgetMax: 50000, estimatedTimeMinutes: 540, indoorOutdoor: "屋内", category: "ダイニングテーブル", templateID: "tpl-garden-table" },
  { id: "dining-4", name: "折りたたみダイニングテーブル", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 16000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "ダイニングテーブル", templateID: "tpl-garden-table" },
  { id: "dining-5", name: "無垢材ダイニングテーブル", difficulty: "上級者", estimatedBudgetMin: 30000, estimatedBudgetMax: 60000, estimatedTimeMinutes: 720, indoorOutdoor: "屋内", category: "ダイニングテーブル", templateID: "tpl-garden-table" },
  { id: "dining-6", name: "カフェ風ダイニングテーブル", difficulty: "中級者", estimatedBudgetMin: 12000, estimatedBudgetMax: 22000, estimatedTimeMinutes: 360, indoorOutdoor: "屋内", category: "ダイニングテーブル", templateID: "tpl-garden-table" },
  { id: "dining-7", name: "コンパクトダイニングテーブル", difficulty: "初心者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内", category: "ダイニングテーブル", templateID: "tpl-garden-table" },
  { id: "dining-8", name: "丸型ダイニングテーブル", difficulty: "上級者", estimatedBudgetMin: 18000, estimatedBudgetMax: 35000, estimatedTimeMinutes: 480, indoorOutdoor: "屋内", category: "ダイニングテーブル", templateID: "tpl-garden-table" },
  { id: "dining-9", name: "ハイテーブル（バーカウンター）", difficulty: "中級者", estimatedBudgetMin: 12000, estimatedBudgetMax: 22000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "ダイニングテーブル", templateID: "tpl-garden-table" },
  { id: "dining-10", name: "子供用ローダイニングテーブル", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "ダイニングテーブル", templateID: "tpl-garden-table" },
  { id: "desk-1", name: "シンプルデスク", difficulty: "初心者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 150, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "desk-2", name: "L字型デスク", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 20000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "desk-3", name: "ガレージ用作業台", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "desk-4", name: "スタンディングデスク", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 16000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "desk-5", name: "引き出し付きデスク", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 20000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "desk-6", name: "棚付きデスク", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 16000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "desk-7", name: "DIY作業台", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 20000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "desk-8", name: "キッチン作業台", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 16000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "desk-9", name: "パソコンデスク", difficulty: "初心者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 150, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "desk-10", name: "子供用学習デスク", difficulty: "初心者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 150, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "desk-11", name: "在宅勤務デスク（仕切り付き）", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 20000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "desk-12", name: "ソーイングデスク", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "desk-13", name: "アート作業台", difficulty: "初心者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "desk-14", name: "2段デスク（ロフトタイプ）", difficulty: "上級者", estimatedBudgetMin: 18000, estimatedBudgetMax: 35000, estimatedTimeMinutes: 480, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "desk-15", name: "折りたたみ壁掛けデスク", difficulty: "中級者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内", category: "デスク・作業台", templateID: "tpl-tv-stand" },
  { id: "bookshelf-1", name: "シンプル本棚", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "本棚", templateID: "tpl-shelf-basic" },
  { id: "bookshelf-2", name: "大型本棚", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 20000, estimatedTimeMinutes: 300, indoorOutdoor: "屋内", category: "本棚", templateID: "tpl-shelf-basic" },
  { id: "bookshelf-3", name: "文庫本棚（スリム）", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "本棚", templateID: "tpl-shelf-basic" },
  { id: "bookshelf-4", name: "壁面一体本棚", difficulty: "上級者", estimatedBudgetMin: 20000, estimatedBudgetMax: 40000, estimatedTimeMinutes: 600, indoorOutdoor: "屋内", category: "本棚", templateID: "tpl-shelf-basic" },
  { id: "bookshelf-5", name: "漫画本棚", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "本棚", templateID: "tpl-shelf-basic" },
  { id: "bookshelf-6", name: "絵本棚（子供用）", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "本棚", templateID: "tpl-shelf-basic" },
  { id: "bookshelf-7", name: "スリム本棚", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "本棚", templateID: "tpl-shelf-basic" },
  { id: "bookshelf-8", name: "コーナー本棚", difficulty: "中級者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内", category: "本棚", templateID: "tpl-shelf-basic" },
  { id: "bookshelf-9", name: "マガジンラック", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内", category: "本棚", templateID: "tpl-shelf-basic" },
  { id: "bookshelf-10", name: "飾り棚一体型本棚", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 16000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "本棚", templateID: "tpl-shelf-basic" },
  { id: "hanger-1", name: "シンプルハンガーラック", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "ハンガーラック", templateID: "tpl-hanger-rack" },
  { id: "hanger-2", name: "2段ハンガーラック", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "ハンガーラック", templateID: "tpl-hanger-rack" },
  { id: "hanger-3", name: "壁付けハンガーラック", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内", category: "ハンガーラック", templateID: "tpl-hanger-rack" },
  { id: "hanger-4", name: "シューズ付きハンガーラック", difficulty: "中級者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内", category: "ハンガーラック", templateID: "tpl-hanger-rack" },
  { id: "hanger-5", name: "スリムハンガーラック", difficulty: "初心者", estimatedBudgetMin: 2500, estimatedBudgetMax: 5000, estimatedTimeMinutes: 75, indoorOutdoor: "屋内", category: "ハンガーラック", templateID: "tpl-hanger-rack" },
  { id: "hanger-6", name: "帽子掛け付きハンガーラック", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "ハンガーラック", templateID: "tpl-hanger-rack" },
  { id: "hanger-7", name: "子供用ハンガーラック", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内", category: "ハンガーラック", templateID: "tpl-hanger-rack" },
  { id: "hanger-8", name: "クローゼット追加ハンガー", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内", category: "ハンガーラック", templateID: "tpl-hanger-rack" },
  { id: "hanger-9", name: "突っ張りハンガーラック", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "ハンガーラック", templateID: "tpl-hanger-rack" },
  { id: "hanger-10", name: "ウォークインクローゼット用ラック", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 16000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "ハンガーラック", templateID: "tpl-hanger-rack" },
  { id: "kids-1", name: "子供用ローテーブル", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "子供用家具", templateID: "tpl-garden-table" },
  { id: "kids-2", name: "キッズチェア", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "子供用家具", templateID: "tpl-bench" },
  { id: "kids-3", name: "砂場ボックス", difficulty: "初心者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋外", category: "子供用家具", templateID: "tpl-compost-box" },
  { id: "kids-4", name: "ブランコ", difficulty: "中級者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋外", category: "子供用家具", templateID: "tpl-bench" },
  { id: "kids-5", name: "秘密基地（プレイハウス）", difficulty: "上級者", estimatedBudgetMin: 25000, estimatedBudgetMax: 50000, estimatedTimeMinutes: 720, indoorOutdoor: "屋外", category: "子供用家具", templateID: "tpl-compost-box" },
  { id: "kids-6", name: "子供用ベッドフレーム", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 20000, estimatedTimeMinutes: 360, indoorOutdoor: "屋内", category: "子供用家具", templateID: "tpl-bench" },
  { id: "kids-7", name: "キッズ棚", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "子供用家具", templateID: "tpl-shelf-basic" },
  { id: "kids-8", name: "子供用おもちゃ箱", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "子供用家具", templateID: "tpl-compost-box" },
  { id: "kids-9", name: "キッズ用工作台", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "子供用家具", templateID: "tpl-tv-stand" },
  { id: "kids-10", name: "キャンプ用キッズチェア", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 60, indoorOutdoor: "屋外", category: "子供用家具", templateID: "tpl-bench" },
  { id: "storage-1", name: "木製物置（小型）", difficulty: "中級者", estimatedBudgetMin: 15000, estimatedBudgetMax: 30000, estimatedTimeMinutes: 480, indoorOutdoor: "屋外", category: "物置・収納", templateID: "tpl-compost-box" },
  { id: "storage-2", name: "ガーデン収納ボックス", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 300, indoorOutdoor: "屋外", category: "物置・収納", templateID: "tpl-compost-box" },
  { id: "storage-3", name: "バルコニー収納ボックス", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 240, indoorOutdoor: "屋外", category: "物置・収納", templateID: "tpl-compost-box" },
  { id: "storage-4", name: "工具収納ボックス", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "物置・収納", templateID: "tpl-compost-box" },
  { id: "storage-5", name: "薪棚", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 150, indoorOutdoor: "屋外", category: "物置・収納", templateID: "tpl-shelf-basic" },
  { id: "storage-6", name: "自転車置き場（屋根付き）", difficulty: "上級者", estimatedBudgetMin: 20000, estimatedBudgetMax: 40000, estimatedTimeMinutes: 600, indoorOutdoor: "屋外", category: "物置・収納", templateID: "tpl-wood-deck" },
  { id: "storage-7", name: "BBQ道具収納ボックス", difficulty: "初心者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 150, indoorOutdoor: "屋外", category: "物置・収納", templateID: "tpl-compost-box" },
  { id: "storage-8", name: "庭道具収納ラック", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋外", category: "物置・収納", templateID: "tpl-shelf-basic" },
  { id: "storage-9", name: "物置兼作業台", difficulty: "上級者", estimatedBudgetMin: 20000, estimatedBudgetMax: 40000, estimatedTimeMinutes: 600, indoorOutdoor: "屋外", category: "物置・収納", templateID: "tpl-compost-box" },
  { id: "storage-10", name: "灯油缶収納ラック", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋外", category: "物置・収納", templateID: "tpl-shelf-basic" },
  { id: "fence-1", name: "木製目隠しフェンス", difficulty: "中級者", estimatedBudgetMin: 10000, estimatedBudgetMax: 20000, estimatedTimeMinutes: 360, indoorOutdoor: "屋外", category: "ガーデンフェンス", templateID: "tpl-wood-deck" },
  { id: "fence-2", name: "ラティスフェンス", difficulty: "初心者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋外", category: "ガーデンフェンス", templateID: "tpl-wood-deck" },
  { id: "fence-3", name: "花壇フェンス", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋外", category: "ガーデンフェンス", templateID: "tpl-wood-deck" },
  { id: "fence-4", name: "ガーデンゲート", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 16000, estimatedTimeMinutes: 300, indoorOutdoor: "屋外", category: "ガーデンフェンス", templateID: "tpl-wood-deck" },
  { id: "fence-5", name: "ピケットフェンス", difficulty: "初心者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋外", category: "ガーデンフェンス", templateID: "tpl-wood-deck" },
  { id: "fence-6", name: "低木フェンス（枕木風）", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋外", category: "ガーデンフェンス", templateID: "tpl-wood-deck" },
  { id: "fence-7", name: "バルコニー目隠しパネル", difficulty: "初心者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 150, indoorOutdoor: "屋外", category: "ガーデンフェンス", templateID: "tpl-wood-deck" },
  { id: "fence-8", name: "アジアン風竹フェンス", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 240, indoorOutdoor: "屋外", category: "ガーデンフェンス", templateID: "tpl-wood-deck" },
  { id: "fence-9", name: "犬用ペットフェンス", difficulty: "中級者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 240, indoorOutdoor: "屋外", category: "ガーデンフェンス", templateID: "tpl-wood-deck" },
  { id: "fence-10", name: "道路境界フェンス（高型）", difficulty: "上級者", estimatedBudgetMin: 20000, estimatedBudgetMax: 40000, estimatedTimeMinutes: 600, indoorOutdoor: "屋外", category: "ガーデンフェンス", templateID: "tpl-wood-deck" },
  { id: "entrance-1", name: "玄関ベンチ付きシューズラック", difficulty: "中級者", estimatedBudgetMin: 8000, estimatedBudgetMax: 15000, estimatedTimeMinutes: 240, indoorOutdoor: "屋内", category: "玄関収納", templateID: "tpl-shoe-rack" },
  { id: "entrance-2", name: "傘立て一体型収納", difficulty: "初心者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 120, indoorOutdoor: "屋内", category: "玄関収納", templateID: "tpl-shoe-rack" },
  { id: "entrance-3", name: "玄関飾り台（花台）", difficulty: "初心者", estimatedBudgetMin: 2500, estimatedBudgetMax: 5000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "玄関収納", templateID: "tpl-flower-box" },
  { id: "entrance-4", name: "スツール付き収納", difficulty: "中級者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内", category: "玄関収納", templateID: "tpl-bench" },
  { id: "entrance-5", name: "玄関コートハンガー", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "玄関収納", templateID: "tpl-shelf-basic" },
  { id: "entrance-6", name: "キーボックス付きラック", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "玄関収納", templateID: "tpl-shelf-basic" },
  { id: "entrance-7", name: "アウトドア用品収納ラック", difficulty: "中級者", estimatedBudgetMin: 6000, estimatedBudgetMax: 12000, estimatedTimeMinutes: 180, indoorOutdoor: "屋内", category: "玄関収納", templateID: "tpl-shelf-basic" },
  { id: "entrance-8", name: "ランドセル棚", difficulty: "初心者", estimatedBudgetMin: 3000, estimatedBudgetMax: 6000, estimatedTimeMinutes: 90, indoorOutdoor: "屋内", category: "玄関収納", templateID: "tpl-shelf-basic" },
  { id: "sign-1", name: "ウッドサイン看板", difficulty: "初心者", estimatedBudgetMin: 1500, estimatedBudgetMax: 3000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内・屋外", category: "看板・インテリア", templateID: "tpl-flower-box" },
  { id: "sign-2", name: "ガーデン表札", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 90, indoorOutdoor: "屋外", category: "看板・インテリア", templateID: "tpl-flower-box" },
  { id: "sign-3", name: "店舗看板（木製）", difficulty: "中級者", estimatedBudgetMin: 5000, estimatedBudgetMax: 10000, estimatedTimeMinutes: 180, indoorOutdoor: "屋外", category: "看板・インテリア", templateID: "tpl-flower-box" },
  { id: "sign-4", name: "メニューボード", difficulty: "初心者", estimatedBudgetMin: 2000, estimatedBudgetMax: 4000, estimatedTimeMinutes: 60, indoorOutdoor: "屋内・屋外", category: "看板・インテリア", templateID: "tpl-flower-box" },
  { id: "sign-5", name: "アンティーク風木製看板", difficulty: "中級者", estimatedBudgetMin: 4000, estimatedBudgetMax: 8000, estimatedTimeMinutes: 150, indoorOutdoor: "屋内・屋外", category: "看板・インテリア", templateID: "tpl-flower-box" },
] as const;

async function seed() {
  console.log(`Seeding ${ALL_USE_CASES.length} use cases...`);
  const col = db.collection("useCases");
  let batch = db.batch();
  let count = 0;
  const commits: Promise<FirebaseFirestore.WriteResult[]>[] = [];

  for (const uc of ALL_USE_CASES) {
    const categorySlug = TEMPLATE_CATEGORY_SLUG[uc.templateID] ?? uc.category;
    batch.set(col.doc(uc.id), {
      name: uc.name,
      category: uc.category,
      categorySlug,
      templateID: uc.templateID,
      difficulty: uc.difficulty,
      estimatedBudgetMin: uc.estimatedBudgetMin,
      estimatedBudgetMax: uc.estimatedBudgetMax,
      estimatedTimeMinutes: uc.estimatedTimeMinutes,
      indoorOutdoor: uc.indoorOutdoor,
      supportedRetailers: ["カインズ", "コメリ", "コーナン", "DCM"],
      description: `${uc.name}のDIY設計図。`,
      imageAlt: `${uc.name}のDIY設計図`,
      createdAt: FieldValue.serverTimestamp(),
    });
    count++;
    if (count % 499 === 0) {
      commits.push(batch.commit());
      batch = db.batch();
    }
  }
  commits.push(batch.commit());
  await Promise.all(commits);
  console.log(`✅ ${count} 件を useCases コレクションに書き込みました。`);
}

seed().catch((e) => { console.error(e); process.exit(1); });
